-- The AR reminder email template, editable in the app by the five named senders. One row,
-- placeholders {dba} and {trigger}; the invoice table is always generated by the job and
-- inserted between intro and closing (the template can't break the numbers).
create table if not exists public.email_template (
  id int primary key default 1 check (id = 1),
  subject text not null default 'Payment reminder — Wizard Trees — {dba}',
  intro text not null default 'Hi {dba} team,

This is a friendly automated reminder from Wizard Trees. {trigger}

Here is the current statement of open invoices on your account:',
  closing text not null default 'If payment is already on its way, please disregard this note — and thank you! If anything looks off, just reply to this email and we''ll straighten it out.

Thank you for your business,
Wizard Trees — Accounts Receivable',
  updated_at timestamptz not null default now(),
  updated_by text
);
insert into public.email_template (id) values (1) on conflict (id) do nothing;
alter table public.email_template enable row level security;
drop policy if exists email_template_read on public.email_template;
create policy email_template_read on public.email_template for select to authenticated
  using ((auth.jwt() ->> 'email') ilike '%@wizardtrees.com');
drop policy if exists email_template_write on public.email_template;
create policy email_template_write on public.email_template for update to authenticated
  using (lower(auth.jwt() ->> 'email') in
    ('gianni@wizardtrees.com','victoria@wizardtrees.com','amanda@wizardtrees.com',
     'jesse@wizardtrees.com','joanna@wizardtrees.com'))
  with check (lower(auth.jwt() ->> 'email') in
    ('gianni@wizardtrees.com','victoria@wizardtrees.com','amanda@wizardtrees.com',
     'jesse@wizardtrees.com','joanna@wizardtrees.com'));
-- no insert/delete for clients: the single row is seeded here

-- +30 days cadence joins the other three offsets
alter table public.email_reminders add column if not exists d30_after boolean not null default false;
