-- NY schedule-workbook spellings → dispensaries.aliases
-- Lets the Schedule calendar resolve a NY visit to its registry store (BA report
-- link + post-visit report pairing). Generated from high-confidence matches only
-- (address agreement, exact/de-spaced name, unique prefix). Safe to re-run.

update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'BFF')
 where id = '925d638f-fcda-412f-b690-b876deb2e56e' and not (coalesce(aliases,'{}') @> array['BFF']);   -- Blue Forest Farms Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Bayside Cannabis')
 where id = '36de67df-c951-4bca-85d0-c7bf581a5dc2' and not (coalesce(aliases,'{}') @> array['Bayside Cannabis']);   -- Bayside Cannabis Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Beleaf BK')
 where id = 'a15d4e51-1da1-4370-b35c-ad24d8083fd7' and not (coalesce(aliases,'{}') @> array['Beleaf BK']);   -- Beleaf - Brooklyn
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Bleu Leaf')
 where id = '0f8f1564-7282-4088-89a9-fa458e4c9dc7' and not (coalesce(aliases,'{}') @> array['Bleu Leaf']);   -- Bleu Leaf Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Bliss + Lex')
 where id = '3a5e86ff-1f9c-4957-b887-2670b31f2cd7' and not (coalesce(aliases,'{}') @> array['Bliss + Lex']);   -- Bliss & Lex
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Bliss and Lex')
 where id = '3a5e86ff-1f9c-4957-b887-2670b31f2cd7' and not (coalesce(aliases,'{}') @> array['Bliss and Lex']);   -- Bliss & Lex
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Blue Forest Farms')
 where id = '925d638f-fcda-412f-b690-b876deb2e56e' and not (coalesce(aliases,'{}') @> array['Blue Forest Farms']);   -- Blue Forest Farms Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'CONBUD LES')
 where id = 'd58ae165-8d09-4d1f-97bd-02b4439fe0ba' and not (coalesce(aliases,'{}') @> array['CONBUD LES']);   -- CONBUD - LES - Delancey St
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Canna Planet (Kingston)')
 where id = '54cf9db5-0c9e-4953-9645-67046f1b0d76' and not (coalesce(aliases,'{}') @> array['Canna Planet (Kingston)']);   -- Canna Planet - Kingston
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Canna Planet Kingston')
 where id = '54cf9db5-0c9e-4953-9645-67046f1b0d76' and not (coalesce(aliases,'{}') @> array['Canna Planet Kingston']);   -- Canna Planet - Kingston
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Cannabis Realm SV')
 where id = '3496cf3b-d5f7-4d96-bc33-7755b73ea9e8' and not (coalesce(aliases,'{}') @> array['Cannabis Realm SV']);   -- Cannabis Realm of New York - Spring Valley
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Cannabis Realm WP')
 where id = 'bffbfcb8-a6db-44e3-9200-74e115dd21fd' and not (coalesce(aliases,'{}') @> array['Cannabis Realm WP']);   -- Cannabis Realm of New York - White Plains
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Cannablooms')
 where id = '821c85a5-fd25-489f-ad6d-735c433b62c2' and not (coalesce(aliases,'{}') @> array['Cannablooms']);   -- Canna Blooms Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Chronic BK')
 where id = 'bcdb80fc-04b0-4e4f-afca-99c38e1d8f84' and not (coalesce(aliases,'{}') @> array['Chronic BK']);   -- Chronic Brooklyn
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'ConBud LES')
 where id = 'd58ae165-8d09-4d1f-97bd-02b4439fe0ba' and not (coalesce(aliases,'{}') @> array['ConBud LES']);   -- CONBUD - LES - Delancey St
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Conbud LES')
 where id = 'd58ae165-8d09-4d1f-97bd-02b4439fe0ba' and not (coalesce(aliases,'{}') @> array['Conbud LES']);   -- CONBUD - LES - Delancey St
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Conbud Les')
 where id = 'd58ae165-8d09-4d1f-97bd-02b4439fe0ba' and not (coalesce(aliases,'{}') @> array['Conbud Les']);   -- CONBUD - LES - Delancey St
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'County Rd Cannabis')
 where id = 'c47e64d3-b682-4959-9c0a-5874a07d18d8' and not (coalesce(aliases,'{}') @> array['County Rd Cannabis']);   -- County Road Cannabis
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'County rd cannabis')
 where id = 'c47e64d3-b682-4959-9c0a-5874a07d18d8' and not (coalesce(aliases,'{}') @> array['County rd cannabis']);   -- County Road Cannabis
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Culture House Greenpoint')
 where id = '5dba074e-6ca9-438e-9686-4dda66d8b0c9' and not (coalesce(aliases,'{}') @> array['Culture House Greenpoint']);   -- Culture House - Greenpoint
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Culture House- midtown')
 where id = '11bf67fc-196a-4093-880f-7f3f2341d622' and not (coalesce(aliases,'{}') @> array['Culture House- midtown']);   -- Culture House
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Culture house Greenpoint')
 where id = '5dba074e-6ca9-438e-9686-4dda66d8b0c9' and not (coalesce(aliases,'{}') @> array['Culture house Greenpoint']);   -- Culture House - Greenpoint
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'DISPO')
 where id = 'd5c2dd00-c652-41b1-a3cb-a7e15f01d326' and not (coalesce(aliases,'{}') @> array['DISPO']);   -- DISPO Cannabis Club
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Daily Green')
 where id = '549ccaf4-ab7d-4f11-847b-1353b326cbac' and not (coalesce(aliases,'{}') @> array['Daily Green']);   -- The Daily Green
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Dankley-fidi')
 where id = '00fb5d50-261f-4916-9263-9bf2b8fbad37' and not (coalesce(aliases,'{}') @> array['Dankley-fidi']);   -- Dankley Fidi
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Demarinos')
 where id = '2ed5a6a0-2780-4824-910d-4ec5f270bdec' and not (coalesce(aliases,'{}') @> array['Demarinos']);   -- DeMarinos Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Elevate')
 where id = '6322317b-5f63-4361-a08d-36e70e3301cb' and not (coalesce(aliases,'{}') @> array['Elevate']);   -- Elevate Cannabis Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Emerald Bushwick')
 where id = '94b0f103-e80c-4a27-a749-eac70f876a7d' and not (coalesce(aliases,'{}') @> array['Emerald Bushwick']);   -- The Emerald Dispensary - Bushwick
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Farmers Choice')
 where id = '557b57d6-d6f2-43bc-93b5-0a3aa360b145' and not (coalesce(aliases,'{}') @> array['Farmers Choice']);   -- Farmers Choice Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flavor Factory')
 where id = '2632dcbc-ca8a-4893-8b84-3e61e89c2edc' and not (coalesce(aliases,'{}') @> array['Flavor Factory']);   -- The Flavor Factory
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'FlowerShak')
 where id = '0e19b46f-c37f-473e-99ac-d7e27569d100' and not (coalesce(aliases,'{}') @> array['FlowerShak']);   -- Flower Shak
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery (East Village)')
 where id = 'bb6e084e-b2be-4711-afef-d20244a9bcb8' and not (coalesce(aliases,'{}') @> array['Flowery (East Village)']);   -- The Flowery East Village
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery (Queens)')
 where id = 'ed33e988-4fb4-46ae-90e5-441d7473968b' and not (coalesce(aliases,'{}') @> array['Flowery (Queens)']);   -- The Flowery - Queens
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery (Richmond)')
 where id = '8f75fe61-8023-49da-80ec-92d07633d735' and not (coalesce(aliases,'{}') @> array['Flowery (Richmond)']);   -- The Flowery - Staten Island - Richmond Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery (chinatown)')
 where id = '8dbbb8e0-4bfc-4cf5-9e71-2b6f3afdcd04' and not (coalesce(aliases,'{}') @> array['Flowery (chinatown)']);   -- The Flowery - Chinatown
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery (east village)')
 where id = 'bb6e084e-b2be-4711-afef-d20244a9bcb8' and not (coalesce(aliases,'{}') @> array['Flowery (east village)']);   -- The Flowery East Village
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery (veterans)')
 where id = '8f728448-445e-43d4-807e-eff17acea877' and not (coalesce(aliases,'{}') @> array['Flowery (veterans)']);   -- The Flowery - Staten Island - Veterans Rd
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery BK')
 where id = 'fb7a5034-ebdb-433b-b332-5999ea93f620' and not (coalesce(aliases,'{}') @> array['Flowery BK']);   -- The Flowery - Brooklyn
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery BX')
 where id = 'e0b7e007-8eec-4070-9564-b19cb9605fb8' and not (coalesce(aliases,'{}') @> array['Flowery BX']);   -- The Flowery - Bronx
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery China town')
 where id = '8dbbb8e0-4bfc-4cf5-9e71-2b6f3afdcd04' and not (coalesce(aliases,'{}') @> array['Flowery China town']);   -- The Flowery - Chinatown
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery Haverstraw')
 where id = '2a139f23-6fd9-459e-aa92-5c1514352d0a' and not (coalesce(aliases,'{}') @> array['Flowery Haverstraw']);   -- The Flowery - Haverstraw
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery Havestraw')
 where id = '2a139f23-6fd9-459e-aa92-5c1514352d0a' and not (coalesce(aliases,'{}') @> array['Flowery Havestraw']);   -- The Flowery - Haverstraw
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery Newburgh')
 where id = 'becb8ecb-7043-49ac-b35a-9c5e72070fa9' and not (coalesce(aliases,'{}') @> array['Flowery Newburgh']);   -- The Flowery - Newburgh
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery Queens')
 where id = 'ed33e988-4fb4-46ae-90e5-441d7473968b' and not (coalesce(aliases,'{}') @> array['Flowery Queens']);   -- The Flowery - Queens
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery Richmond')
 where id = '8f75fe61-8023-49da-80ec-92d07633d735' and not (coalesce(aliases,'{}') @> array['Flowery Richmond']);   -- The Flowery - Staten Island - Richmond Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery SOHO')
 where id = '35f0d03b-e8b7-4d8f-b5df-7087333224b6' and not (coalesce(aliases,'{}') @> array['Flowery SOHO']);   -- The Flowery - SOHO
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery UWS')
 where id = 'bd859dff-97eb-4d44-989a-5d405ea771c4' and not (coalesce(aliases,'{}') @> array['Flowery UWS']);   -- The Flowery - Upper West Side
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery Veterans')
 where id = '8f728448-445e-43d4-807e-eff17acea877' and not (coalesce(aliases,'{}') @> array['Flowery Veterans']);   -- The Flowery - Staten Island - Veterans Rd
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery WV')
 where id = '34bda39a-76c1-41d5-860b-a778dc12ca8c' and not (coalesce(aliases,'{}') @> array['Flowery WV']);   -- The Flowery - West Village
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery West Village')
 where id = '34bda39a-76c1-41d5-860b-a778dc12ca8c' and not (coalesce(aliases,'{}') @> array['Flowery West Village']);   -- The Flowery - West Village
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery china town')
 where id = '8dbbb8e0-4bfc-4cf5-9e71-2b6f3afdcd04' and not (coalesce(aliases,'{}') @> array['Flowery china town']);   -- The Flowery - Chinatown
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowery east village')
 where id = 'bb6e084e-b2be-4711-afef-d20244a9bcb8' and not (coalesce(aliases,'{}') @> array['Flowery east village']);   -- The Flowery East Village
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flowey (Upper West Side)')
 where id = 'bd859dff-97eb-4d44-989a-5d405ea771c4' and not (coalesce(aliases,'{}') @> array['Flowey (Upper West Side)']);   -- The Flowery - Upper West Side
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flynnstoned BayRige')
 where id = '400bd950-2776-40a8-9337-54d796950aac' and not (coalesce(aliases,'{}') @> array['Flynnstoned BayRige']);   -- FlynnStoned - Bay Ridge
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flynnstoned Baytowne')
 where id = '079a0029-b9a4-42de-a26d-c09daa2d7874' and not (coalesce(aliases,'{}') @> array['Flynnstoned Baytowne']);   -- FlynnStoned - Baytowne
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flynnstoned Chelsea')
 where id = '137cdf0c-fba1-4f32-a52e-b4d115f672f7' and not (coalesce(aliases,'{}') @> array['Flynnstoned Chelsea']);   -- FlynnStoned - Chelsea
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flynnstoned Oswego')
 where id = '10501eee-f500-4849-a72a-09a3fc975b53' and not (coalesce(aliases,'{}') @> array['Flynnstoned Oswego']);   -- FlynnStoned - Oswego
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Flynnstoned- Bayridge')
 where id = '400bd950-2776-40a8-9337-54d796950aac' and not (coalesce(aliases,'{}') @> array['Flynnstoned- Bayridge']);   -- FlynnStoned - Bay Ridge
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Good Life (Rochester)')
 where id = 'b3697194-9a58-4c7f-8970-7de2206e3a8b' and not (coalesce(aliases,'{}') @> array['Good Life (Rochester)']);   -- Good Life Collective - Rochester
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Good Life Collective Rochester')
 where id = 'b3697194-9a58-4c7f-8970-7de2206e3a8b' and not (coalesce(aliases,'{}') @> array['Good Life Collective Rochester']);   -- Good Life Collective - Rochester
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Good Life Rochester')
 where id = 'b3697194-9a58-4c7f-8970-7de2206e3a8b' and not (coalesce(aliases,'{}') @> array['Good Life Rochester']);   -- Good Life Collective - Rochester
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Goodlife')
 where id = 'b3697194-9a58-4c7f-8970-7de2206e3a8b' and not (coalesce(aliases,'{}') @> array['Goodlife']);   -- Good Life Collective - Rochester
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Green Cup')
 where id = 'ed8213c4-d377-4641-8e47-cd472d3a0536' and not (coalesce(aliases,'{}') @> array['Green Cup']);   -- Greencup
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Green Flower Wellne')
 where id = '88da5c01-f8c7-4ffa-a733-09e67a142496' and not (coalesce(aliases,'{}') @> array['Green Flower Wellne']);   -- Green Flower Wellness - Floral Park
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Green Philosophy')
 where id = 'ddd1338e-fa70-44d6-9504-7488783b1d2b' and not (coalesce(aliases,'{}') @> array['Green Philosophy']);   -- Green Philosophy 716
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Green Wellness Hillside')
 where id = '88da5c01-f8c7-4ffa-a733-09e67a142496' and not (coalesce(aliases,'{}') @> array['Green Wellness Hillside']);   -- Green Flower Wellness - Floral Park
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Happy Munkey BK')
 where id = '5ce59cde-39fa-4981-b90e-7c5256eed710' and not (coalesce(aliases,'{}') @> array['Happy Munkey BK']);   -- Happy Munkey - Fulton St.
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Happy Munkey Dyckman')
 where id = '8a211e1b-1d47-41a8-8b5d-356630745dd4' and not (coalesce(aliases,'{}') @> array['Happy Munkey Dyckman']);   -- Happy Munkey - Dyckman St.
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Happy Munkey Fulton')
 where id = '5ce59cde-39fa-4981-b90e-7c5256eed710' and not (coalesce(aliases,'{}') @> array['Happy Munkey Fulton']);   -- Happy Munkey - Fulton St.
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Happy Munkey- Dyckman')
 where id = '8a211e1b-1d47-41a8-8b5d-356630745dd4' and not (coalesce(aliases,'{}') @> array['Happy Munkey- Dyckman']);   -- Happy Munkey - Dyckman St.
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Happy Munkey-fulton')
 where id = '5ce59cde-39fa-4981-b90e-7c5256eed710' and not (coalesce(aliases,'{}') @> array['Happy Munkey-fulton']);   -- Happy Munkey - Fulton St.
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Happy munkey dyckman')
 where id = '8a211e1b-1d47-41a8-8b5d-356630745dd4' and not (coalesce(aliases,'{}') @> array['Happy munkey dyckman']);   -- Happy Munkey - Dyckman St.
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Happy munkey fulton')
 where id = '5ce59cde-39fa-4981-b90e-7c5256eed710' and not (coalesce(aliases,'{}') @> array['Happy munkey fulton']);   -- Happy Munkey - Fulton St.
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Hibernica')
 where id = '6041e83f-1fdf-4061-8afd-aa3459ad2c8c' and not (coalesce(aliases,'{}') @> array['Hibernica']);   -- Hibernica Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Hibrary Club')
 where id = 'd43b4c69-aeb6-424a-873c-8be14befd854' and not (coalesce(aliases,'{}') @> array['Hibrary Club']);   -- The Hibrary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'High City')
 where id = '7f8185a6-0af6-4e8e-8836-8f2b77297afa' and not (coalesce(aliases,'{}') @> array['High City']);   -- High City Cannabis - Astoria
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'High Life Health')
 where id = '7ff4e214-cd64-4e27-808b-2334814bf261' and not (coalesce(aliases,'{}') @> array['High Life Health']);   -- Highlife Health
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Highest Standards')
 where id = '488e8b55-396e-46ca-818b-58eacef61267' and not (coalesce(aliases,'{}') @> array['Highest Standards']);   -- Highest Standards - Manhattan
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Hii (Bedford ave)')
 where id = '3303420b-a4c8-451d-82f2-2db914375693' and not (coalesce(aliases,'{}') @> array['Hii (Bedford ave)']);   -- Hii - NYC
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Hii (bayridge)')
 where id = '4b83e35a-9dc8-44f2-9cad-eacc9fd283e9' and not (coalesce(aliases,'{}') @> array['Hii (bayridge)']);   -- Hii - BayRidge
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Hii (bedford ave)')
 where id = '3303420b-a4c8-451d-82f2-2db914375693' and not (coalesce(aliases,'{}') @> array['Hii (bedford ave)']);   -- Hii - NYC
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Hii Bay Ridge')
 where id = '4b83e35a-9dc8-44f2-9cad-eacc9fd283e9' and not (coalesce(aliases,'{}') @> array['Hii Bay Ridge']);   -- Hii - BayRidge
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Hii bayridge')
 where id = '4b83e35a-9dc8-44f2-9cad-eacc9fd283e9' and not (coalesce(aliases,'{}') @> array['Hii bayridge']);   -- Hii - BayRidge
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Hii- Bay Ridge')
 where id = '4b83e35a-9dc8-44f2-9cad-eacc9fd283e9' and not (coalesce(aliases,'{}') @> array['Hii- Bay Ridge']);   -- Hii - BayRidge
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Indoor Trees Fashion Ave')
 where id = '4d092945-34d4-4466-90e6-6c0a189481b1' and not (coalesce(aliases,'{}') @> array['Indoor Trees Fashion Ave']);   -- Indoor Treez - Fashion Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Indoor Treez (fashion ave)')
 where id = '4d092945-34d4-4466-90e6-6c0a189481b1' and not (coalesce(aliases,'{}') @> array['Indoor Treez (fashion ave)']);   -- Indoor Treez - Fashion Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Indoor Treez fashion ave')
 where id = '4d092945-34d4-4466-90e6-6c0a189481b1' and not (coalesce(aliases,'{}') @> array['Indoor Treez fashion ave']);   -- Indoor Treez - Fashion Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Kaya Bliss')
 where id = '1477e6f1-dbe4-4af6-9c1f-a5a72fe0e2aa' and not (coalesce(aliases,'{}') @> array['Kaya Bliss']);   -- Kaya Bliss - Bay Ridge
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Kush Klub')
 where id = '4e5134f4-9a1c-454e-a915-388705829b37' and not (coalesce(aliases,'{}') @> array['Kush Klub']);   -- KushKlub
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Kushmart Kings Highway')
 where id = 'c0a01812-0710-4b45-a642-fbb93c7e03ba' and not (coalesce(aliases,'{}') @> array['Kushmart Kings Highway']);   -- KushMart - Brooklyn - Kings Highway
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Kushmart brookyln')
 where id = 'c0a01812-0710-4b45-a642-fbb93c7e03ba' and not (coalesce(aliases,'{}') @> array['Kushmart brookyln']);   -- KushMart - Brooklyn - Kings Highway
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'LICC')
 where id = 'e8e7f744-b32b-4baa-9a6b-10f9fdc797db' and not (coalesce(aliases,'{}') @> array['LICC']);   -- Long Island Cannabis Club
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Leaf Plug Amherst')
 where id = 'a281f6d5-267c-4436-8f16-652181d90e11' and not (coalesce(aliases,'{}') @> array['Leaf Plug Amherst']);   -- Leaf Plug - Buffalo
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Leaf Plug Springville')
 where id = 'c0d87a82-3a05-4b54-a9f5-84e2d3653d76' and not (coalesce(aliases,'{}') @> array['Leaf Plug Springville']);   -- Leaf Plug - Springville
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Lenox Hill')
 where id = '98ac5c4d-7c13-4d94-81e5-15299b6c1a9d' and not (coalesce(aliases,'{}') @> array['Lenox Hill']);   -- Lenox Hill Cannabis Co.
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Lenox Hill Cannabis')
 where id = '98ac5c4d-7c13-4d94-81e5-15299b6c1a9d' and not (coalesce(aliases,'{}') @> array['Lenox Hill Cannabis']);   -- Lenox Hill Cannabis Co.
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Liberty Buds Queens')
 where id = 'b57157e6-2a39-43b7-ade6-5cc155073576' and not (coalesce(aliases,'{}') @> array['Liberty Buds Queens']);   -- Liberty Buds - Queens
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Liberty buds NYC')
 where id = '7d40789d-cf3a-4ee1-9cb9-5ec07d641d1e' and not (coalesce(aliases,'{}') @> array['Liberty buds NYC']);   -- Liberty Buds
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Liberty buds queens')
 where id = 'b57157e6-2a39-43b7-ade6-5cc155073576' and not (coalesce(aliases,'{}') @> array['Liberty buds queens']);   -- Liberty Buds - Queens
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Lighthouse')
 where id = 'd626aaa7-c45f-4452-a8ad-9ecc6140ee0d' and not (coalesce(aliases,'{}') @> array['Lighthouse']);   -- Lighthouse Cannabis
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Mango')
 where id = 'd7e8d218-6bc6-454e-ba0b-5116de555b51' and not (coalesce(aliases,'{}') @> array['Mango']);   -- Mango Cannabis
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Middletown Indoor Cannabis')
 where id = '000aea98-b8ec-4d76-bd7b-0a3112949c5a' and not (coalesce(aliases,'{}') @> array['Middletown Indoor Cannabis']);   -- Middletown Indoor Cannabis Co
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Middletown indoor Cannabis')
 where id = '000aea98-b8ec-4d76-bd7b-0a3112949c5a' and not (coalesce(aliases,'{}') @> array['Middletown indoor Cannabis']);   -- Middletown Indoor Cannabis Co
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Middletown indoor cannabis')
 where id = '000aea98-b8ec-4d76-bd7b-0a3112949c5a' and not (coalesce(aliases,'{}') @> array['Middletown indoor cannabis']);   -- Middletown Indoor Cannabis Co
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Mindset')
 where id = '68b8b85c-13ad-437d-99d9-72488e3e80b6' and not (coalesce(aliases,'{}') @> array['Mindset']);   -- Mindset Cannabis Shop
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Misfits')
 where id = 'cb4b681b-db66-44e3-bd86-6c7829878685' and not (coalesce(aliases,'{}') @> array['Misfits']);   -- Misfits Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Munchies')
 where id = '529031a0-a66f-43d7-b149-6e787b0b8e89' and not (coalesce(aliases,'{}') @> array['Munchies']);   -- Munchies Dispensary NY
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'NUNAHARVEST')
 where id = '88eb32bd-ef5f-4875-80a8-240c904e555c' and not (coalesce(aliases,'{}') @> array['NUNAHARVEST']);   -- Nuna Harvest
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'NYCC (5th ave)')
 where id = 'd6af8c73-9699-43a8-a8c8-eb3ada4cd58d' and not (coalesce(aliases,'{}') @> array['NYCC (5th ave)']);   -- NY Cannabis Co. - 5th Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'NYCC (9th ave)')
 where id = '9029f2e9-d432-46f1-88f4-bd3dc945cc5d' and not (coalesce(aliases,'{}') @> array['NYCC (9th ave)']);   -- NY Cannabis Co. - 9th Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'NYCC 5th ave')
 where id = 'd6af8c73-9699-43a8-a8c8-eb3ada4cd58d' and not (coalesce(aliases,'{}') @> array['NYCC 5th ave']);   -- NY Cannabis Co. - 5th Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'NYCC 9th ave')
 where id = '9029f2e9-d432-46f1-88f4-bd3dc945cc5d' and not (coalesce(aliases,'{}') @> array['NYCC 9th ave']);   -- NY Cannabis Co. - 9th Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'New Metro (wish list)')
 where id = '31da5d9d-6517-444e-ab8a-bb954808acc3' and not (coalesce(aliases,'{}') @> array['New Metro (wish list)']);   -- New Metro
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'OZ Dispencery')
 where id = 'ec4f0ca7-f4fa-4c46-94b2-79fee826893d' and not (coalesce(aliases,'{}') @> array['OZ Dispencery']);   -- Oz Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'OZ Dispo')
 where id = 'ec4f0ca7-f4fa-4c46-94b2-79fee826893d' and not (coalesce(aliases,'{}') @> array['OZ Dispo']);   -- Oz Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'OZ dispo')
 where id = 'ec4f0ca7-f4fa-4c46-94b2-79fee826893d' and not (coalesce(aliases,'{}') @> array['OZ dispo']);   -- Oz Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Oz Dispo')
 where id = 'ec4f0ca7-f4fa-4c46-94b2-79fee826893d' and not (coalesce(aliases,'{}') @> array['Oz Dispo']);   -- Oz Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Peace, Love & Bud')
 where id = '37cf5449-063f-492c-ab9a-0f3470953295' and not (coalesce(aliases,'{}') @> array['Peace, Love & Bud']);   -- Peace Love & Bud
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Peace, Love, & Bud')
 where id = '37cf5449-063f-492c-ab9a-0f3470953295' and not (coalesce(aliases,'{}') @> array['Peace, Love, & Bud']);   -- Peace Love & Bud
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Peace, Love, Bud')
 where id = '37cf5449-063f-492c-ab9a-0f3470953295' and not (coalesce(aliases,'{}') @> array['Peace, Love, Bud']);   -- Peace Love & Bud
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Phinest Buds')
 where id = '93ef06bf-9bc5-4bbc-ab9f-62ced760b079' and not (coalesce(aliases,'{}') @> array['Phinest Buds']);   -- The Phinest Buds Cannabis Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Plainum Leaf')
 where id = '8ddb44f9-96e6-4923-a9bd-41435734902d' and not (coalesce(aliases,'{}') @> array['Plainum Leaf']);   -- Platinum Leaf
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'QCD BK')
 where id = 'a4341083-fe9e-4441-b723-b78ff00b5cd3' and not (coalesce(aliases,'{}') @> array['QCD BK']);   -- Quality Control Dispensary - Brooklyn
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'QCD SI')
 where id = '046a7535-f704-4765-bfcf-fceb5cff62d1' and not (coalesce(aliases,'{}') @> array['QCD SI']);   -- Quality Control Dispensary - Staten Island
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Quality Control BK')
 where id = 'a4341083-fe9e-4441-b723-b78ff00b5cd3' and not (coalesce(aliases,'{}') @> array['Quality Control BK']);   -- Quality Control Dispensary - Brooklyn
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Quality Control Bk')
 where id = 'a4341083-fe9e-4441-b723-b78ff00b5cd3' and not (coalesce(aliases,'{}') @> array['Quality Control Bk']);   -- Quality Control Dispensary - Brooklyn
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Quality Control Dispensary BK')
 where id = 'a4341083-fe9e-4441-b723-b78ff00b5cd3' and not (coalesce(aliases,'{}') @> array['Quality Control Dispensary BK']);   -- Quality Control Dispensary - Brooklyn
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Quality Control Dispensary SI')
 where id = '046a7535-f704-4765-bfcf-fceb5cff62d1' and not (coalesce(aliases,'{}') @> array['Quality Control Dispensary SI']);   -- Quality Control Dispensary - Staten Island
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Quality Control SI')
 where id = '046a7535-f704-4765-bfcf-fceb5cff62d1' and not (coalesce(aliases,'{}') @> array['Quality Control SI']);   -- Quality Control Dispensary - Staten Island
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Quality Control- Staten Island')
 where id = '046a7535-f704-4765-bfcf-fceb5cff62d1' and not (coalesce(aliases,'{}') @> array['Quality Control- Staten Island']);   -- Quality Control Dispensary - Staten Island
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Quality control SI')
 where id = '046a7535-f704-4765-bfcf-fceb5cff62d1' and not (coalesce(aliases,'{}') @> array['Quality control SI']);   -- Quality Control Dispensary - Staten Island
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Quality roots BK')
 where id = 'a57f2d7d-e9ea-4943-a27b-4cd3b24cf66a' and not (coalesce(aliases,'{}') @> array['Quality roots BK']);   -- Quality Roots
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'REVELRY')
 where id = '0065e7bc-e69a-4d0c-b8fa-32d64a37add7' and not (coalesce(aliases,'{}') @> array['REVELRY']);   -- Revelry Event
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'RNR')
 where id = '6fa3bbee-5975-42ec-8289-bc8ff1b320fd' and not (coalesce(aliases,'{}') @> array['RNR']);   -- RNR Bushwick Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'STELLAR')
 where id = 'e5b40e3d-973d-4799-ae2b-1aa2706b27d1' and not (coalesce(aliases,'{}') @> array['STELLAR']);   -- Stellar Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'STRAIN STARS FARM')
 where id = '988d8d50-0b89-47da-985f-707c2f002b06' and not (coalesce(aliases,'{}') @> array['STRAIN STARS FARM']);   -- Strain Stars Dispensary - Farmingdale
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'STRAIN STARS RIVER')
 where id = '1b50935c-44e7-42e9-99ca-e45bba72ddde' and not (coalesce(aliases,'{}') @> array['STRAIN STARS RIVER']);   -- Strain Stars Dispensary - Riverhead
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'STRAIN STARS WHITE PLAINS')
 where id = '2c19f73d-03d0-4596-b0a0-3e244f50e0b1' and not (coalesce(aliases,'{}') @> array['STRAIN STARS WHITE PLAINS']);   -- Strain Stars Dispensary - White Plains
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Sesh')
 where id = 'be2048bd-bc37-460a-bd5b-e825f7da47f1' and not (coalesce(aliases,'{}') @> array['Sesh']);   -- SeshNYC
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'SkyHigh club')
 where id = 'b6b9faea-2287-47f7-b296-0e740f9a7d9a' and not (coalesce(aliases,'{}') @> array['SkyHigh club']);   -- Sky High Club
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Sofa Club')
 where id = '9fd13677-83de-436f-b5fa-9218a4a7dfa9' and not (coalesce(aliases,'{}') @> array['Sofa Club']);   -- SOFACLUB - Midtown
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'SofaClub midtown')
 where id = '9fd13677-83de-436f-b5fa-9218a4a7dfa9' and not (coalesce(aliases,'{}') @> array['SofaClub midtown']);   -- SOFACLUB - Midtown
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'SofaClub- 56th st')
 where id = '9fd13677-83de-436f-b5fa-9218a4a7dfa9' and not (coalesce(aliases,'{}') @> array['SofaClub- 56th st']);   -- SOFACLUB - Midtown
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Star Life')
 where id = '2408c8c9-c0d8-4103-ba85-bc6b329c8105' and not (coalesce(aliases,'{}') @> array['Star Life']);   -- Starlife
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Stash Master')
 where id = 'a6aeb754-1a93-427a-9006-5f642d316f95' and not (coalesce(aliases,'{}') @> array['Stash Master']);   -- Stashmaster
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Stash master')
 where id = 'a6aeb754-1a93-427a-9006-5f642d316f95' and not (coalesce(aliases,'{}') @> array['Stash master']);   -- Stashmaster
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'State of Mind- Albany')
 where id = '8eb1c0d2-5f72-4c14-9045-c9a75e2e5d4b' and not (coalesce(aliases,'{}') @> array['State of Mind- Albany']);   -- State of Mind Dispensary - Albany
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'State of Mind- Latham')
 where id = '5f3ac380-5d59-4e20-b647-56b15726a435' and not (coalesce(aliases,'{}') @> array['State of Mind- Latham']);   -- State of Mind Dispensary - Latham
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Stellar')
 where id = 'e5b40e3d-973d-4799-ae2b-1aa2706b27d1' and not (coalesce(aliases,'{}') @> array['Stellar']);   -- Stellar Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Strain Stars (WP)')
 where id = '2c19f73d-03d0-4596-b0a0-3e244f50e0b1' and not (coalesce(aliases,'{}') @> array['Strain Stars (WP)']);   -- Strain Stars Dispensary - White Plains
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Strain Stars Farm')
 where id = '988d8d50-0b89-47da-985f-707c2f002b06' and not (coalesce(aliases,'{}') @> array['Strain Stars Farm']);   -- Strain Stars Dispensary - Farmingdale
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Strain Stars Farmindale')
 where id = '988d8d50-0b89-47da-985f-707c2f002b06' and not (coalesce(aliases,'{}') @> array['Strain Stars Farmindale']);   -- Strain Stars Dispensary - Farmingdale
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Strain Stars Farmingdale')
 where id = '988d8d50-0b89-47da-985f-707c2f002b06' and not (coalesce(aliases,'{}') @> array['Strain Stars Farmingdale']);   -- Strain Stars Dispensary - Farmingdale
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Strain Stars Riverhead')
 where id = '1b50935c-44e7-42e9-99ca-e45bba72ddde' and not (coalesce(aliases,'{}') @> array['Strain Stars Riverhead']);   -- Strain Stars Dispensary - Riverhead
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Strain Stars riverhead')
 where id = '1b50935c-44e7-42e9-99ca-e45bba72ddde' and not (coalesce(aliases,'{}') @> array['Strain Stars riverhead']);   -- Strain Stars Dispensary - Riverhead
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Strain Stars- Farmingdale')
 where id = '988d8d50-0b89-47da-985f-707c2f002b06' and not (coalesce(aliases,'{}') @> array['Strain Stars- Farmingdale']);   -- Strain Stars Dispensary - Farmingdale
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Strain stars WP')
 where id = '2c19f73d-03d0-4596-b0a0-3e244f50e0b1' and not (coalesce(aliases,'{}') @> array['Strain stars WP']);   -- Strain Stars Dispensary - White Plains
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Strains For Life 2-9pm')
 where id = '486f3d5b-f01d-49ee-a647-1a95130e8ae8' and not (coalesce(aliases,'{}') @> array['Strains For Life 2-9pm']);   -- Strains for Life
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Strains for Life 5-9pm')
 where id = '486f3d5b-f01d-49ee-a647-1a95130e8ae8' and not (coalesce(aliases,'{}') @> array['Strains for Life 5-9pm']);   -- Strains for Life
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Superfly')
 where id = '5452d422-7f1f-4b0f-9c0e-108fee354097' and not (coalesce(aliases,'{}') @> array['Superfly']);   -- Superfly Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'TORCHES LAUNCH PARTY')
 where id = 'c4d201c1-90a7-48aa-b2f8-c7687ac3bfcd' and not (coalesce(aliases,'{}') @> array['TORCHES LAUNCH PARTY']);   -- Torches
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'TORCHES PARTY!')
 where id = 'c4d201c1-90a7-48aa-b2f8-c7687ac3bfcd' and not (coalesce(aliases,'{}') @> array['TORCHES PARTY!']);   -- Torches
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Terp Bro Ozone')
 where id = '9dfd1f8a-1ccd-48f1-8f13-10410cf23450' and not (coalesce(aliases,'{}') @> array['Terp Bro Ozone']);   -- Terp Bros - Ozone Park
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Terp Bros- Astoria')
 where id = '12dedf43-506f-4ea0-85cd-9cfbe60e9039' and not (coalesce(aliases,'{}') @> array['Terp Bros- Astoria']);   -- Terp Bros - Astoria
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Terp Bros- Ozone')
 where id = '9dfd1f8a-1ccd-48f1-8f13-10410cf23450' and not (coalesce(aliases,'{}') @> array['Terp Bros- Ozone']);   -- Terp Bros - Ozone Park
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Terp bros Astoria')
 where id = '12dedf43-506f-4ea0-85cd-9cfbe60e9039' and not (coalesce(aliases,'{}') @> array['Terp bros Astoria']);   -- Terp Bros - Astoria
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery - East Village')
 where id = 'bb6e084e-b2be-4711-afef-d20244a9bcb8' and not (coalesce(aliases,'{}') @> array['The Flowery - East Village']);   -- The Flowery East Village
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery - Havestraw')
 where id = '2a139f23-6fd9-459e-aa92-5c1514352d0a' and not (coalesce(aliases,'{}') @> array['The Flowery - Havestraw']);   -- The Flowery - Haverstraw
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery - Newburg')
 where id = 'becb8ecb-7043-49ac-b35a-9c5e72070fa9' and not (coalesce(aliases,'{}') @> array['The Flowery - Newburg']);   -- The Flowery - Newburgh
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery - Richmond Rd')
 where id = '8f75fe61-8023-49da-80ec-92d07633d735' and not (coalesce(aliases,'{}') @> array['The Flowery - Richmond Rd']);   -- The Flowery - Staten Island - Richmond Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery - UWS')
 where id = 'bd859dff-97eb-4d44-989a-5d405ea771c4' and not (coalesce(aliases,'{}') @> array['The Flowery - UWS']);   -- The Flowery - Upper West Side
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery - Veterns Rd')
 where id = '8f728448-445e-43d4-807e-eff17acea877' and not (coalesce(aliases,'{}') @> array['The Flowery - Veterns Rd']);   -- The Flowery - Staten Island - Veterans Rd
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery BK')
 where id = 'fb7a5034-ebdb-433b-b332-5999ea93f620' and not (coalesce(aliases,'{}') @> array['The Flowery BK']);   -- The Flowery - Brooklyn
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery Newburgh')
 where id = 'becb8ecb-7043-49ac-b35a-9c5e72070fa9' and not (coalesce(aliases,'{}') @> array['The Flowery Newburgh']);   -- The Flowery - Newburgh
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery Richmond')
 where id = '8f75fe61-8023-49da-80ec-92d07633d735' and not (coalesce(aliases,'{}') @> array['The Flowery Richmond']);   -- The Flowery - Staten Island - Richmond Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery Veterans road')
 where id = '8f728448-445e-43d4-807e-eff17acea877' and not (coalesce(aliases,'{}') @> array['The Flowery Veterans road']);   -- The Flowery - Staten Island - Veterans Rd
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flowery- BX')
 where id = 'e0b7e007-8eec-4070-9564-b19cb9605fb8' and not (coalesce(aliases,'{}') @> array['The Flowery- BX']);   -- The Flowery - Bronx
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Flwoery BK')
 where id = 'fb7a5034-ebdb-433b-b332-5999ea93f620' and not (coalesce(aliases,'{}') @> array['The Flwoery BK']);   -- The Flowery - Brooklyn
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The Hibrary Club BK')
 where id = 'd43b4c69-aeb6-424a-873c-8be14befd854' and not (coalesce(aliases,'{}') @> array['The Hibrary Club BK']);   -- The Hibrary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The flowery (richmond)')
 where id = '8f75fe61-8023-49da-80ec-92d07633d735' and not (coalesce(aliases,'{}') @> array['The flowery (richmond)']);   -- The Flowery - Staten Island - Richmond Ave
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The flowery BK')
 where id = 'fb7a5034-ebdb-433b-b332-5999ea93f620' and not (coalesce(aliases,'{}') @> array['The flowery BK']);   -- The Flowery - Brooklyn
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The flowery Newburgh')
 where id = 'becb8ecb-7043-49ac-b35a-9c5e72070fa9' and not (coalesce(aliases,'{}') @> array['The flowery Newburgh']);   -- The Flowery - Newburgh
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The flowery Veterans')
 where id = '8f728448-445e-43d4-807e-eff17acea877' and not (coalesce(aliases,'{}') @> array['The flowery Veterans']);   -- The Flowery - Staten Island - Veterans Rd
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The flowery- Queens')
 where id = 'ed33e988-4fb4-46ae-90e5-441d7473968b' and not (coalesce(aliases,'{}') @> array['The flowery- Queens']);   -- The Flowery - Queens
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'The flowery- west village')
 where id = '34bda39a-76c1-41d5-860b-a778dc12ca8c' and not (coalesce(aliases,'{}') @> array['The flowery- west village']);   -- The Flowery - West Village
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Toke Yonkers')
 where id = '8cb78b10-3778-4732-b25f-21f4689de907' and not (coalesce(aliases,'{}') @> array['Toke Yonkers']);   -- Toke New York
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Toke- rockland')
 where id = 'db17adf1-75cb-4aa9-83ce-e961f5f48cdf' and not (coalesce(aliases,'{}') @> array['Toke- rockland']);   -- Toke Rockland
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Toke-rockland')
 where id = 'db17adf1-75cb-4aa9-83ce-e961f5f48cdf' and not (coalesce(aliases,'{}') @> array['Toke-rockland']);   -- Toke Rockland
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Token')
 where id = '1e41a546-2a92-4a7f-b71b-01ff54232ed4' and not (coalesce(aliases,'{}') @> array['Token']);   -- Token Cannabis Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Tree House (Nyack)')
 where id = 'a5893a60-8c55-4bfd-b4c6-22413507b7bc' and not (coalesce(aliases,'{}') @> array['Tree House (Nyack)']);   -- Treehouse Cannabis
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'TreeHouse')
 where id = 'a5893a60-8c55-4bfd-b4c6-22413507b7bc' and not (coalesce(aliases,'{}') @> array['TreeHouse']);   -- Treehouse Cannabis
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'TreeHouse Nyack')
 where id = 'a5893a60-8c55-4bfd-b4c6-22413507b7bc' and not (coalesce(aliases,'{}') @> array['TreeHouse Nyack']);   -- Treehouse Cannabis
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Treehouse')
 where id = 'a5893a60-8c55-4bfd-b4c6-22413507b7bc' and not (coalesce(aliases,'{}') @> array['Treehouse']);   -- Treehouse Cannabis
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Treehouse- Nyack')
 where id = 'a5893a60-8c55-4bfd-b4c6-22413507b7bc' and not (coalesce(aliases,'{}') @> array['Treehouse- Nyack']);   -- Treehouse Cannabis
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Twenty8grams')
 where id = '6593ca25-87f0-4ecb-aad4-bf7323ecb7b8' and not (coalesce(aliases,'{}') @> array['Twenty8grams']);   -- Twenty8Gramz Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Twenty8gramz')
 where id = '6593ca25-87f0-4ecb-aad4-bf7323ecb7b8' and not (coalesce(aliases,'{}') @> array['Twenty8gramz']);   -- Twenty8Gramz Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Union Chill')
 where id = 'f9b3419b-50c6-40b3-9a42-96c2f8d3169c' and not (coalesce(aliases,'{}') @> array['Union Chill']);   -- Union Chill Cannabis Company
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Urban Leaf')
 where id = '1fd41e80-e734-4f77-a26a-a2e007d92f73' and not (coalesce(aliases,'{}') @> array['Urban Leaf']);   -- Urban Leaf Cannabis Dispensary
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Valley Green')
 where id = '5dbc0bbd-b567-4f6d-9f4f-f843f2c5c099' and not (coalesce(aliases,'{}') @> array['Valley Green']);   -- Valley Greens
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Yeti')
 where id = '9cb03e9d-2fc6-4e0c-b890-82c4ace8415e' and not (coalesce(aliases,'{}') @> array['Yeti']);   -- Yeti Canna
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Yeti Cannabis')
 where id = '9cb03e9d-2fc6-4e0c-b890-82c4ace8415e' and not (coalesce(aliases,'{}') @> array['Yeti Cannabis']);   -- Yeti Canna
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'ZenZest')
 where id = 'e0972618-14b0-4531-8b95-641b5a6562cf' and not (coalesce(aliases,'{}') @> array['ZenZest']);   -- ZenZest Cannabis Dispensary - Queens
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'cannabis reserve new rochelle')
 where id = 'f49561a8-ebd4-4547-828d-aed164ede766' and not (coalesce(aliases,'{}') @> array['cannabis reserve new rochelle']);   -- The Cannabis Reserve
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'flowery bx')
 where id = 'e0b7e007-8eec-4070-9564-b19cb9605fb8' and not (coalesce(aliases,'{}') @> array['flowery bx']);   -- The Flowery - Bronx
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'flowery uws')
 where id = 'bd859dff-97eb-4d44-989a-5d405ea771c4' and not (coalesce(aliases,'{}') @> array['flowery uws']);   -- The Flowery - Upper West Side
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'highest standards')
 where id = '488e8b55-396e-46ca-818b-58eacef61267' and not (coalesce(aliases,'{}') @> array['highest standards']);   -- Highest Standards - Manhattan
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'stellar')
 where id = 'e5b40e3d-973d-4799-ae2b-1aa2706b27d1' and not (coalesce(aliases,'{}') @> array['stellar']);   -- Stellar Dispensary

-- Hand-added: the sheet writes the Queens-style hyphenated street number ("219-17
-- Hillside Ave") while the registry stores it de-hyphenated ("21917 Hillside Ave"),
-- which reads as a 5-digit ZIP to the address matcher, so this pair never auto-linked.
-- Same street + same zip 11427 = the same store.
update public.dispensaries set aliases = array_append(coalesce(aliases,'{}'), 'Dankley Queens')
 where name = 'Dankley Canna' and not (coalesce(aliases,'{}') @> array['Dankley Queens']);
